version: '3'

services:
  traefik:
    image: traefik:v2.0
    container_name: traefik
    depends_on:
      - consul
      - express-gateway
    command:
      - "--providers.consul.endpoint=consul:8500"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

  consul:
    image: hashicorp/consul:v1.15.0
    container_name: consul 
    command: "agent -server -ui -bootstrap-expect=1 -client=0.0.0.0"
    ports:
      - 8500:8500
    labels:
      - "de.wi2021a.gridRole=hub"
    volumes:
      - "./consul/data:/consul/data"

#  express-gateway:
#    image: express-gateway:1.16.11
#    container_name: express-gateway
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.api-gateway.rule=Host(`api-gateway.example.com`)"
#      - "traefik.http.routers.api-gateway.entrypoints=web"
#      - "traefik.http.services.api-gateway.loadbalancer.server.port=80"
#    environment:
#      - "CONSUL_HTTP_ADDR=http://consul:8500"




